version: '2'

services:
  piqu-original: &defaults
    image: piqu:latest
    build:
      context: .
    volumes:
      - ./piqu-original:/myapp
    ports:
      - "4200:4200"
      - "35729:35729"


  npm:
    <<: *defaults
    entrypoint: ['/usr/local/bin/npm']

  bower:
    <<: *defaults
    entrypoint: ['/usr/local/bin/bower', '--allow-root']

  server:
    <<: *defaults
    command: server --watcher polling
    ports:
      - "4200:4200"
      - "35729:35729"
