version: '2'

services:
  piqu-original: &original
    image: piqu:latest
    build:
      context: .
    volumes:
      - ./piqu-original:/myapp
    ports:
      - "4200:4200"
      - "35729:35729"

  piqu-updated: &updated
    image: piqu:latest
    build:
      context: .
    volumes:
      - ./piqu-updated:/myapp
    ports:
      - "4200:4200"
      - "35729:35729"


  npm-original:
    <<: *original
    entrypoint: ['/usr/local/bin/npm']

  bower-original:
    <<: *original
    entrypoint: ['/usr/local/bin/bower', '--allow-root']

  server-original:
    <<: *original
    command: server --watcher polling
    ports:
      - "4200:4200"
      - "35729:35729"


  npm-updated:
    <<: *updated
    entrypoint: ['/usr/local/bin/npm']

  bower-updated:
    <<: *updated
    entrypoint: ['/usr/local/bin/bower', '--allow-root']

  server-updated:
    <<: *updated
    command: server --watcher polling
    ports:
      - "4200:4200"
      - "35729:35729"
